INSERT INTO "career" ("career_code", "career_name", "source", "status") VALUES
('1',	'Tổng Bí thư, Thường trực Ban Bí thư, Ban Bí thư, Ủy viên Bộ Chính trị, Ủy viên Ban Chấp hành Trung ương Đảng',	'phuongchau',	't'),
('2',	'Bí thư, Phó Bí thư Đảng ủy cơ quan trung ương',	'phuongchau',	't'),
('3',	'Bí thư, Phó Bí thư Đảng ủy khối trực thuộc trung ương',	'phuongchau',	't'),
('4',	'Trưởng ban, Phó Trưởng ban Đảng và tương đương thuộc cấp trung ương',	'phuongchau',	't'),
('5',	'Trợ lý Ủy viên Bộ Chính trị',	'phuongchau',	't'),
('6',	'Vụ trưởng, Phó Vụ trưởng và tương đương',	'phuongchau',	't'),
('7',	'Bí thư Tỉnh ủy, Phó Bí thư Tỉnh ủy, Ủy viên Ban Chấp hành Đảng bộ cấp tỉnh',	'phuongchau',	't'),
('8',	'Bí thư, Phó Bí thư Đảng ủy sở, ban, ngành cấp tỉnh',	'phuongchau',	't'),
('9',	'Bí thư, Phó Bí thư Đảng ủy khối cơ quan cấp tỉnh',	'phuongchau',	't'),
('10',	'Trưởng ban, Phó Trưởng ban Đảng và tương đương thuộc cấp tỉnh',	'phuongchau',	't'),
('11',	'Bí thư Huyện ủy, Phó Bí thư Huyện ủy, Ủy viên Ban Chấp hành Đảng bộ cấp huyện',	'phuongchau',	't'),
('12',	'Bí thư, Phó Bí thư Đảng Ủy ban, ngành cấp huyện',	'phuongchau',	't'),
('13',	'Trưởng ban, Phó Trưởng ban Đảng và tương đương thuộc cấp huyện',	'phuongchau',	't'),
('14',	'Bí thư, Phó Bí thư Đảng ủy cấp xã',	'phuongchau',	't'),
('15',	'Bí thư, Phó Bí thư Đảng ủy',	'phuongchau',	't'),
('16',	'Chủ tịch Quốc hội, Phó Chủ tịch Quốc hội, Ủy viên thường vụ Quốc hội',	'phuongchau',	't'),
('17',	'Chủ nhiệm, Phó Chủ nhiệm Ủy ban và tương đương làm việc tại Văn phòng Quốc hội',	'phuongchau',	't'),
('18',	'Vụ trưởng, Phó Vụ trưởng và tương đương',	'phuongchau',	't'),
('19',	'Chủ tịch nước, Phó Chủ tịch nước',	'phuongchau',	't'),
('20',	'Chủ nhiệm, Phó Chủ nhiệm tương đương Bộ trưởng, Thứ trưởng và tương đương làm việc tại Văn phòng Chủ tịch nước',	'phuongchau',	't'),
('21',	'Vụ trưởng, Phó Vụ trưởng và tương đương',	'phuongchau',	't'),
('22',	'Thủ tướng, Phó Thủ tướng Chính phủ',	'phuongchau',	't'),
('23',	'Chủ nhiệm, Phó Chủ nhiệm và tương đương làm việc tại Văn phòng Chính phủ',	'phuongchau',	't'),
('24',	'Vụ trưởng, Phó Vụ trưởng và tương đương',	'phuongchau',	't'),
('25',	'Bộ trưởng, Thứ trưởng và tương đương của các bộ, ngành, các cơ quan ngang bộ, các cơ quan thuộc Chính phủ',	'phuongchau',	't'),
('26',	'Trợ lý Bộ trưởng Bộ Ngoại giao',	'phuongchau',	't'),
('27',	'Vụ trưởng, Phó Vụ trưởng, Trưởng ban, Phó Trưởng ban và tương đương',	'phuongchau',	't'),
('28',	'Tổng cục trưởng, Phó Tổng cục trưởng và tương đương',	'phuongchau',	't'),
('29',	'Vụ trưởng, Phó Vụ trưởng, Trưởng ban, Phó Trưởng ban và tương đương',	'phuongchau',	't'),
('30',	'Chánh án, Phó Chánh án Tòa án nhân dân tối cao và cấp cao; Viện trưởng, Phó Viện trưởng Viện Kiểm sát nhân dân tối cao và cấp cao',	'phuongchau',	't'),
('31',	'Vụ trưởng, Phó Vụ trưởng và tương đương làm việc ở Tòa án nhân dân tối cao và cấp cao và Viện Kiểm sát nhân dân tối cao và cấp cao',	'phuongchau',	't'),
('32',	'Chánh án, Phó Chánh án Tòa án nhân dân; Viện trưởng, Phó Viện trưởng Viện Kiểm sát nhân dân cấp tỉnh',	'phuongchau',	't'),
('33',	'Chánh án, Phó Chánh án Tòa án nhân dân cấp huyện',	'phuongchau',	't'),
('34',	'Chánh án, Phó Chánh án Tòa án khác (trừ Tòa án Quân sự) do luật định',	'phuongchau',	't'),
('35',	'Chủ tịch, Phó Chủ tịch và Thường trực Hội đồng nhân dân cấp tỉnh',	'phuongchau',	't'),
('36',	'Trưởng ban, Phó Trưởng ban và tương đương trong các cơ quan của Hội đồng nhân dân cấp tỉnh',	'phuongchau',	't'),
('37',	'Chủ tịch, Phó Chủ tịch và Thường trực Hội đồng nhân dân cấp huyện',	'phuongchau',	't'),
('38',	'Trưởng ban, Phó Trưởng ban và tương đương trong các cơ quan của Hội đồng nhân dân cấp huyện',	'phuongchau',	't'),
('39',	'Chủ tịch, Phó Chủ tịch Hội đồng nhân dân cấp xã',	'phuongchau',	't'),
('40',	'Chủ tịch, Phó Chủ tịch và Ủy viên thường trực Ủy ban nhân dân cấp tỉnh',	'phuongchau',	't'),
('41',	'Chủ tịch, Phó Chủ tịch và Ủy viên thường trực Ủy ban nhân dân cấp huyện',	'phuongchau',	't'),
('42',	'Chủ tịch, Phó Chủ tịch Ủy ban nhân dân cấp xã',	'phuongchau',	't'),
('43',	'Trưởng ngành, Phó Trưởng ngành, ban, sở và tương đương của các cơ quan chuyên môn cấp tỉnh',	'phuongchau',	't'),
('44',	'Trưởng ngành, Phó Trưởng ngành, ban và tương đương của các cơ quan chuyên môn cấp huyện',	'phuongchau',	't'),
('45',	'Chủ tịch, Phó Chủ tịch',	'phuongchau',	't'),
('46',	'Ủy viên cấp trung ương',	'phuongchau',	't'),
('47',	'Vụ trưởng, Phó Vụ trưởng và tương đương cấp trung ương',	'phuongchau',	't'),
('48',	'Ủy viên cấp tỉnh',	'phuongchau',	't'),
('49',	'Ủy viên cấp huyện',	'phuongchau',	't'),
('50',	'Chủ tịch, Phó Chủ tịch',	'phuongchau',	't'),
('51',	'Ủy viên của Tổng Liên đoàn Lao động Việt Nam',	'phuongchau',	't'),
('52',	'Vụ trưởng, Phó Vụ trưởng và tương đương của Tổng Liên đoàn Lao động Việt Nam',	'phuongchau',	't'),
('53',	'Ủy viên trở lên của Liên đoàn Lao động cấp tỉnh',	'phuongchau',	't'),
('54',	'Ủy viên trở lên của Liên đoàn Lao động cấp huyện',	'phuongchau',	't'),
('55',	'Chủ tịch, Phó Chủ tịch tổ chức công đoàn cơ quan bộ, ngành ở trung ương',	'phuongchau',	't'),
('56',	'Chủ tịch, Phó Chủ tịch tổ chức công đoàn doanh nghiệp và các tổ chức sự nghiệp',	'phuongchau',	't'),
('57',	'Chủ tịch, Phó Chủ tịch',	'phuongchau',	't'),
('58',	'Chủ tịch, Phó Chủ tịch',	'phuongchau',	't'),
('59',	'Chủ tịch, Phó Chủ tịch Hội đồng quản trị, Tổng giám đốc doanh nghiệp, Phó Tổng giám đốc doanh nghiệp, Chủ tịch, Phó Chủ tịch Hội đồng trường, Hiệu trưởng, Phó Hiệu trưởng trường đại học lớn và tương đương (chuyên trách)',	'phuongchau',	't'),
('60',	'Giám đốc, Phó Giám đốc của các đơn vị sản xuất và triển khai thuộc cơ quan tập đoàn, tổng công ty, trường đại học lớn và tương đương (chuyên trách)',	'phuongchau',	't'),
('155',	'Nhà chuyên môn về quan hệ công chúng',	'phuongchau',	't'),
('417',	'Nhân viên chăm sóc trẻ em',	'phuongchau',	't'),
('61',	'Giám đốc, Phó Giám đốc các đơn vị quản lý thuộc cơ quan Liên hiệp, Tổng công ty, trường đại học lớn và tương đương (chuyên trách)',	'phuongchau',	't'),
('62',	'Giám đốc, Phó Giám đốc công ty, doanh nghiệp, xí nghiệp, hợp tác xã; Hiệu trưởng, Phó Hiệu trưởng trường nhỏ và tương đương (chuyên trách)',	'phuongchau',	't'),
('63',	'Nhà vật lý học và thiên văn học',	'phuongchau',	't'),
('64',	'Nhà khí tượng học',	'phuongchau',	't'),
('65',	'Nhà hóa học',	'phuongchau',	't'),
('66',	'Nhà địa chất, địa vật lý',	'phuongchau',	't'),
('67',	'Nhà toán học',	'phuongchau',	't'),
('68',	'Nhà phân tích nghiên cứu hoạt động',	'phuongchau',	't'),
('69',	'Nhà thống kê',	'phuongchau',	't'),
('70',	'Nhà sinh vật học, thực vật học, động vật học và các chuyên môn liên quan',	'phuongchau',	't'),
('71',	'Nhà trồng trọt',	'phuongchau',	't'),
('72',	'Nhà tư vấn làm vườn',	'phuongchau',	't'),
('73',	'Nhà bệnh học thực vật',	'phuongchau',	't'),
('74',	'Nhà khoa học đất đai',	'phuongchau',	't'),
('75',	'Nhà chăn nuôi',	'phuongchau',	't'),
('76',	'Nhà nuôi cấy tế bào động vật',	'phuongchau',	't'),
('77',	'Nhà nuôi cấy mô thực vật',	'phuongchau',	't'),
('78',	'Nhà tư vấn nuôi trồng thủy sản',	'phuongchau',	't'),
('79',	'Các chuyên gia nông, lâm, thủy sản khác',	'phuongchau',	't'),
('80',	'Nhà chuyên môn về bảo vệ môi trường',	'phuongchau',	't'),
('81',	'Kỹ sư công nghiệp chế biến, chế tạo',	'phuongchau',	't'),
('82',	'Kỹ sư xây dựng',	'phuongchau',	't'),
('83',	'Kỹ sư môi trường',	'phuongchau',	't'),
('84',	'Kỹ sư cơ học, cơ khí',	'phuongchau',	't'),
('85',	'Kỹ sư hóa học',	'phuongchau',	't'),
('86',	'Kỹ sư khai thác mỏ, luyện kim và các nghề liên quan',	'phuongchau',	't'),
('87',	'Kỹ sư kỹ thuật khác chưa được phân vào đâu',	'phuongchau',	't'),
('88',	'Kỹ sư điện',	'phuongchau',	't'),
('89',	'Kỹ sư điện tử',	'phuongchau',	't'),
('90',	'Kỹ sư viễn thông',	'phuongchau',	't'),
('91',	'Kiến trúc sư xây dựng',	'phuongchau',	't'),
('92',	'Kiến trúc sư cảnh quan',	'phuongchau',	't'),
('93',	'Nhà thiết kế trang phục/thời trang, phụ kiện',	'phuongchau',	't'),
('94',	'Nhà thiết kế công nghiệp và sản phẩm',	'phuongchau',	't'),
('95',	'Nhà quy hoạch đô thị',	'phuongchau',	't'),
('96',	'Nhà quy hoạch giao thông khác',	'phuongchau',	't'),
('97',	'Nhà khảo sát chung',	'phuongchau',	't'),
('98',	'Nhà khảo sát đất',	'phuongchau',	't'),
('99',	'Nhà khảo sát thủy văn',	'phuongchau',	't'),
('100',	'Người vẽ bản đồ',	'phuongchau',	't'),
('101',	'Nhà khảo sát và vẽ bản đồ khác',	'phuongchau',	't'),
('102',	'Nhà thiết kế đồ họa và truyền thông đa phương tiện',	'phuongchau',	't'),
('103',	'Bác sỹ đa khoa',	'phuongchau',	't'),
('104',	'Bác sỹ tim mạch',	'phuongchau',	't'),
('105',	'Bác sỹ da liễu',	'phuongchau',	't'),
('106',	'Bác sỹ tiêu hóa',	'phuongchau',	't'),
('107',	'Bác sỹ nội khoa',	'phuongchau',	't'),
('108',	'Bác sỹ ung bướu',	'phuongchau',	't'),
('109',	'Bác sỹ nhi khoa',	'phuongchau',	't'),
('110',	'Bác sỹ hô hấp',	'phuongchau',	't'),
('111',	'Bác sỹ tâm thần',	'phuongchau',	't'),
('112',	'Bác sỹ chuyên khoa khác',	'phuongchau',	't'),
('113',	'Y tá/Điều dưỡng (cao cấp)',	'phuongchau',	't'),
('114',	'Hộ sinh (cao cấp)',	'phuongchau',	't'),
('115',	'Nhà chuyên môn về y học cổ truyền và hỗ trợ',	'phuongchau',	't'),
('116',	'Bác sỹ phụ tá',	'phuongchau',	't'),
('117',	'Bác sỹ thú y',	'phuongchau',	't'),
('118',	'Bác sỹ răng - hàm - mặt',	'phuongchau',	't'),
('119',	'Dược sỹ sản xuất thuốc',	'phuongchau',	't'),
('120',	'Dược sỹ khác',	'phuongchau',	't'),
('121',	'Nhà chuyên môn về vệ sinh môi trường và bệnh nghề nghiệp',	'phuongchau',	't'),
('122',	'Nhà chuyên môn về vật lý trị liệu',	'phuongchau',	't'),
('123',	'Nhà chuyên môn về dinh dưỡng',	'phuongchau',	't'),
('124',	'Bác sỹ thính học và đặc trị các khuyết tật về ngôn ngữ',	'phuongchau',	't'),
('125',	'Nhà chuyên môn về thị lực và nhãn khoa',	'phuongchau',	't'),
('126',	'Nhà chuyên môn khác về sức khỏe chưa được phân vào đâu',	'phuongchau',	't'),
('127',	'Giảng viên đại học và cao học',	'phuongchau',	't'),
('128',	'Giảng viên cao đẳng',	'phuongchau',	't'),
('129',	'Giáo viên trung cấp',	'phuongchau',	't'),
('130',	'Giáo viên trung học phổ thông (cấp III)',	'phuongchau',	't'),
('131',	'Giáo viên trung học cơ sở (cấp II)',	'phuongchau',	't'),
('132',	'Giáo viên tiểu học (cấp I)',	'phuongchau',	't'),
('133',	'Giáo viên mầm non',	'phuongchau',	't'),
('134',	'Chuyên gia về phương pháp giáo dục',	'phuongchau',	't'),
('135',	'Giáo viên theo các nhu cầu đặc biệt',	'phuongchau',	't'),
('136',	'Giáo viên ngôn ngữ khác',	'phuongchau',	't'),
('137',	'Giáo viên âm nhạc khác',	'phuongchau',	't'),
('138',	'Giáo viên nghệ thuật khác',	'phuongchau',	't'),
('139',	'Giáo viên công nghệ thông tin',	'phuongchau',	't'),
('140',	'Nhà chuyên môn giảng dạy khác chưa được phân vào đâu',	'phuongchau',	't'),
('141',	'Kế toán (trừ kế toán thuế)',	'phuongchau',	't'),
('142',	'Kiểm toán',	'phuongchau',	't'),
('143',	'Kế toán thuế',	'phuongchau',	't'),
('144',	'Nhà tư vấn tài chính và đầu tư',	'phuongchau',	't'),
('145',	'Nhà phân tích tài chính',	'phuongchau',	't'),
('146',	'Nhà phân tích rủi ro',	'phuongchau',	't'),
('147',	'Nhà quản lý quỹ đầu tư',	'phuongchau',	't'),
('148',	'Nhà quản lý quỹ ủy thác',	'phuongchau',	't'),
('149',	'Nhà phân tích tài chính và các nhà chuyên môn có liên quan khác',	'phuongchau',	't'),
('150',	'Nhà phân tích tổ chức và quản lý',	'phuongchau',	't'),
('151',	'Nhà chuyên môn về quản trị chính sách',	'phuongchau',	't'),
('152',	'Nhà chuyên môn về nhân sự và nghề nghiệp',	'phuongchau',	't'),
('153',	'Nhà chuyên môn về đào tạo và phát triển nhân viên',	'phuongchau',	't'),
('154',	'Nhà chuyên môn về quảng cáo và tiếp thị',	'phuongchau',	't'),
('156',	'Nhà chuyên môn về bán hàng hóa kỹ thuật và y tế (không bao gồm công nghệ thông tin và truyền thông)',	'phuongchau',	't'),
('157',	'Nhà chuyên môn về bán hàng hóa trong lĩnh vực công nghệ thông tin và truyền thông',	'phuongchau',	't'),
('158',	'Nhà chuyên môn về hải quan của Chính phủ',	'phuongchau',	't'),
('159',	'Nhà chuyên môn về thuế của Chính phủ',	'phuongchau',	't'),
('160',	'Nhà chuyên môn về trợ cấp xã hội của Chính phủ',	'phuongchau',	't'),
('161',	'Nhà chuyên môn về cấp phép của Chính phủ',	'phuongchau',	't'),
('162',	'Kiểm lâm',	'phuongchau',	't'),
('163',	'Nhà ngoại giao',	'phuongchau',	't'),
('164',	'Nhà chuyên môn điều tiết của Chính phủ khác chưa được phân vào đâu',	'phuongchau',	't'),
('165',	'Nhà phân tích/thiết kế hệ thống',	'phuongchau',	't'),
('166',	'Tư vấn quy trình kinh doanh công nghệ thông tin/phân tích kinh doanh',	'phuongchau',	't'),
('167',	'Nhà kiến trúc giải pháp/doanh nghiệp',	'phuongchau',	't'),
('168',	'Nhà phát triển phần mềm',	'phuongchau',	't'),
('169',	'Nhà phát triển web và truyền thông đa phương tiện',	'phuongchau',	't'),
('170',	'Nhà lập trình các ứng dụng',	'phuongchau',	't'),
('171',	'Nhà chuyên môn về phát triển phần mềm ứng dụng và nhà phân tích chưa được phân vào đâu',	'phuongchau',	't'),
('172',	'Nhà quản trị cơ sở dữ liệu',	'phuongchau',	't'),
('173',	'Nhà thiết kế cơ sở dữ liệu',	'phuongchau',	't'),
('174',	'Nhà quản trị hệ thống',	'phuongchau',	't'),
('175',	'Nhà chuyên môn về mạng máy tính',	'phuongchau',	't'),
('176',	'Nhà khoa học dữ liệu',	'phuongchau',	't'),
('177',	'Nhà chuyên môn về mạng và cơ sở dữ liệu',	'phuongchau',	't'),
('178',	'Luật sư tham gia tố tụng',	'phuongchau',	't'),
('179',	'Luật sư tư vấn pháp luật',	'phuongchau',	't'),
('180',	'Luật sư khác',	'phuongchau',	't'),
('181',	'Thẩm phán',	'phuongchau',	't'),
('182',	'Công chứng viên',	'phuongchau',	't'),
('183',	'Thừa phát lại',	'phuongchau',	't'),
('184',	'Nhà chuyên môn về luật khác chưa được phân vào đâu',	'phuongchau',	't'),
('185',	'Nhà chuyên môn về luư trữ và giám tuyển',	'phuongchau',	't'),
('186',	'Thủ thư và các nhà chuyên môn về thông tin liên quan',	'phuongchau',	't'),
('187',	'Nhà kinh tế học',	'phuongchau',	't'),
('188',	'Nhà xã hội học, nhà nhân chủng học và các nghề có liên quan',	'phuongchau',	't'),
('189',	'Nhà triết học, sử học và khoa học chính trị',	'phuongchau',	't'),
('190',	'Nhà tâm lý học',	'phuongchau',	't'),
('191',	'Nhà chuyên môn về tư vấn và công tác xã hội',	'phuongchau',	't'),
('192',	'Nhà chuyên môn về tôn giáo',	'phuongchau',	't'),
('193',	'Nhà văn',	'phuongchau',	't'),
('194',	'Người viết kịch bản',	'phuongchau',	't'),
('195',	'Người viết lời quảng cáo',	'phuongchau',	't'),
('196',	'Người viết tài liệu kỹ thuật',	'phuongchau',	't'),
('197',	'Nhà biên tập kịch bản và kết nối',	'phuongchau',	't'),
('198',	'Biên tập viên xuất bản phẩm',	'phuongchau',	't'),
('199',	'Người viết khác và các nghề liên quan',	'phuongchau',	't'),
('200',	'Nhà báo',	'phuongchau',	't'),
('201',	'Biên tập viên',	'phuongchau',	't'),
('202',	'Phiên dịch',	'phuongchau',	't'),
('203',	'Biên dịch',	'phuongchau',	't'),
('204',	'Nhà ngôn ngữ khác',	'phuongchau',	't'),
('205',	'Nhà điêu khắc',	'phuongchau',	't'),
('206',	'Hoạ sỹ',	'phuongchau',	't'),
('207',	'Người vẽ tranh hoạt họa',	'phuongchau',	't'),
('208',	'Nghệ sỹ hình ảnh khác',	'phuongchau',	't'),
('209',	'Nhạc công',	'phuongchau',	't'),
('210',	'Nhạc sỹ',	'phuongchau',	't'),
('211',	'Nhạc trưởng/giám đốc dàn nhạc/ban nhạc/dàn hợp xướng',	'phuongchau',	't'),
('212',	'Ca sỹ',	'phuongchau',	't'),
('213',	'Nhạc công, ca sỹ và nhạc sỹ khác',	'phuongchau',	't'),
('214',	'Vũ công và biên đạo múa',	'phuongchau',	't'),
('215',	'Đạo diễn, nhà sản xuất phim, sân khấu và các nghề liên quan',	'phuongchau',	't'),
('216',	'Diễn viên',	'phuongchau',	't'),
('217',	'Phát thanh viên trên đài, truyền hình và các phương tiện truyền thông đại chúng khác',	'phuongchau',	't'),
('218',	'Nghệ sỹ sáng tạo và trình diễn liên quan khác chưa được phân vào đâu',	'phuongchau',	't'),
('219',	'Kỹ thuật viên hóa học',	'phuongchau',	't'),
('220',	'Kỹ thuật viên vật lí',	'phuongchau',	't'),
('221',	'Kỹ thuật viên hóa học và vật lí khác',	'phuongchau',	't'),
('222',	'Kỹ thuật viên xây dựng dân dụng',	'phuongchau',	't'),
('223',	'Kỹ thuật viên kết cấu',	'phuongchau',	't'),
('224',	'Kỹ thuật viên xây dựng công trình',	'phuongchau',	't'),
('225',	'Kỹ thuật viên khảo sát đất đai',	'phuongchau',	't'),
('226',	'Kỹ thuật viên xây dựng dân dụng khác',	'phuongchau',	't'),
('227',	'Kỹ thuật viên điện dân dụng chung',	'phuongchau',	't'),
('228',	'Kỹ thuật viên điện dân dụng cao tần',	'phuongchau',	't'),
('229',	'Kỹ thuật viên điện dân dụng khác',	'phuongchau',	't'),
('230',	'Kỹ thuật viên điện tử dân dụng (chung)',	'phuongchau',	't'),
('231',	'Kỹ thuật viên bán dẫn',	'phuongchau',	't'),
('232',	'Kỹ thuật viên thiết bị ghi âm, ghi hình',	'phuongchau',	't'),
('233',	'Kỹ thuật viên thiết bị đo đạc',	'phuongchau',	't'),
('234',	'Kỹ thuật viên điện tử dân dụng khác',	'phuongchau',	't'),
('235',	'Kỹ thuật viên kỹ thuật cơ khí chung',	'phuongchau',	't'),
('236',	'Kỹ thuật viên cơ khí hàng không',	'phuongchau',	't'),
('237',	'Kỹ thuật viên máy tự động',	'phuongchau',	't'),
('238',	'Kỹ thuật viên điều hòa không khí/điện lạnh',	'phuongchau',	't'),
('239',	'Kỹ thuật viên máy móc, công cụ',	'phuongchau',	't'),
('240',	'Người thiết kế khuôn/công cụ',	'phuongchau',	't'),
('241',	'Kỹ thuật viên cơ khí dân dụng khác',	'phuongchau',	't'),
('242',	'Kỹ thuật viên kỹ thuật hóa học',	'phuongchau',	't'),
('243',	'Kỹ thuật viên khai thác mỏ và luyện kim',	'phuongchau',	't'),
('244',	'Kỹ thuật viên phác thảo kỹ thuật',	'phuongchau',	't'),
('245',	'Kỹ thuật viên khoa học vật lý và kỹ thuật chưa được phân vào đâu',	'phuongchau',	't'),
('246',	'Giám sát viên khai thác mỏ',	'phuongchau',	't'),
('247',	'Giám sát viên sản xuất',	'phuongchau',	't'),
('248',	'Giám sát viên xây dựng',	'phuongchau',	't'),
('249',	'Người vận hành trạm hoặc nhà máy phát điện',	'phuongchau',	't'),
('250',	'Người vận hành lò đốt rác và nhà máy xử lý nước',	'phuongchau',	't'),
('251',	'Kiểm soát viên nhà máy xử lý hoá chất',	'phuongchau',	't'),
('252',	'Người vận hành nhà máy lọc dầu và khí tự nhiên',	'phuongchau',	't'),
('253',	'Kiểm soát viên quy trình sản xuất kim loại',	'phuongchau',	't'),
('254',	'Kỹ thuật viên kiểm soát quy trình khác chưa được phân vào đâu',	'phuongchau',	't'),
('255',	'Kỹ thuật viên khoa học sự sống (không kể y tế)',	'phuongchau',	't'),
('256',	'Kỹ thuật viên nông nghiệp',	'phuongchau',	't'),
('257',	'Kỹ thuật viên lâm nghiệp',	'phuongchau',	't'),
('258',	'Kỹ thuật viên nuôi trồng thủy sản',	'phuongchau',	't'),
('259',	'Kỹ thuật viên máy của tàu thủy',	'phuongchau',	't'),
('260',	'Hoa tiêu và nhân viên văn phòng trên tàu',	'phuongchau',	't'),
('261',	'Phi công phương tiện bay và kỹ thuật viên hỗ trợ liên quan',	'phuongchau',	't'),
('262',	'Kiểm soát viên không lưu',	'phuongchau',	't'),
('263',	'Kỹ thuật viên điện tử an toàn không lưu',	'phuongchau',	't'),
('264',	'Kỹ thuật viên siêu âm',	'phuongchau',	't'),
('265',	'Kỹ thuật viên X quang',	'phuongchau',	't'),
('266',	'Kỹ thuật viên thiết bị y tế và hình ảnh khác',	'phuongchau',	't'),
('267',	'Kỹ thuật viên phòng thí nghiệm y tế',	'phuongchau',	't'),
('268',	'Kỹ thuật viên và trợ lý dược',	'phuongchau',	't'),
('269',	'Kỹ thuật viên lắp chân tay giả và chỉnh hình',	'phuongchau',	't'),
('270',	'Người làm và sửa các thiết bị chỉnh hình',	'phuongchau',	't'),
('271',	'Kỹ thuật viên lắp răng giả, chân tay giả và các thiết bị chỉnh hình khác',	'phuongchau',	't'),
('272',	'Y tá/điều dưỡng, kỹ thuật viên chăm sóc bệnh nhân',	'phuongchau',	't'),
('273',	'Hộ sinh',	'phuongchau',	't'),
('274',	'Kỹ thuật viên y học cổ truyền và bổ trợ',	'phuongchau',	't'),
('275',	'Kỹ thuật viên thú y và phụ tá',	'phuongchau',	't'),
('276',	'Phụ tá nha khoa và trị liệu',	'phuongchau',	't'),
('277',	'Kỹ thuật viên ghi chép sổ sách y tế và thông tin về sức khỏe',	'phuongchau',	't'),
('278',	'Nhân viên y tế cộng đồng',	'phuongchau',	't'),
('279',	'Kỹ thuật viên nhãn khoa',	'phuongchau',	't'),
('280',	'Kỹ thuật viên vật lý trị liệu và phụ tá',	'phuongchau',	't'),
('281',	'Nhân viên trợ giúp y tế',	'phuongchau',	't'),
('282',	'Thanh tra viên và cộng tác viên môi trường và sức khỏe nghề nghiệp',	'phuongchau',	't'),
('283',	'Nhân viên cấp cứu',	'phuongchau',	't'),
('284',	'Kỹ thuật viên sức khỏe khác chưa được phân vào đâu',	'phuongchau',	't'),
('285',	'Nhân viên môi giới, buôn bán chứng khoán và tài chính',	'phuongchau',	't'),
('286',	'Nhân viên phụ trách các khoản tín dụng và khoản vay',	'phuongchau',	't'),
('287',	'Kế toán viên',	'phuongchau',	't'),
('288',	'Nhân viên về thống kê và toán học ứng dụng có liên quan',	'phuongchau',	't'),
('289',	'Thẩm định viên/định giá (trừ tài sản vô hình)',	'phuongchau',	't'),
('290',	'Giám định viên',	'phuongchau',	't'),
('291',	'Nhân viên định giá tài sản vô hình',	'phuongchau',	't'),
('292',	'Thủ quỹ',	'phuongchau',	't'),
('293',	'Đại lý môi giới bảo hiểm (gồm cả nhà kế hoạch tài chính độc lập)',	'phuongchau',	't'),
('294',	'Đại diện bảo hiểm và các nhân viên hỗ trợ liên quan khác',	'phuongchau',	't'),
('295',	'Nhân viên đại diện bán hàng hóa thương mại',	'phuongchau',	't'),
('296',	'Nhân viên thu mua',	'phuongchau',	't'),
('297',	'Đại lý thu mua',	'phuongchau',	't'),
('298',	'Nhân viên môi giới thương mại',	'phuongchau',	't'),
('299',	'Nhân viên làm thủ tục thông quan và vận tải hàng hóa',	'phuongchau',	't'),
('300',	'Nhân viên tổ chức hội thảo và sự kiện',	'phuongchau',	't'),
('301',	'Nhân viên môi giới việc làm và nhà thầu',	'phuongchau',	't'),
('302',	'Nhân viên môi giới bất động sản và quản lý tài sản/bất động sản',	'phuongchau',	't'),
('303',	'Nhân viên/đại lý dịch vụ kinh doanh khác chưa được phân vào đâu',	'phuongchau',	't'),
('304',	'Giám sát viên văn phòng',	'phuongchau',	't'),
('305',	'Thư ký luật',	'phuongchau',	't'),
('306',	'Thư ký hành chính và điều hành',	'phuongchau',	't'),
('307',	'Thư ký y tế',	'phuongchau',	't'),
('308',	'Nhân viên hải quan của Chính phủ',	'phuongchau',	't'),
('309',	'Nhân viên thuế của Chính phủ',	'phuongchau',	't'),
('310',	'Nhân viên trợ cấp xã hội của Chính phủ',	'phuongchau',	't'),
('311',	'Nhân viên cấp phép của Chính phủ',	'phuongchau',	't'),
('312',	'Kiểm lâm',	'phuongchau',	't'),
('313',	'Nhân viên điều tiết của Chính phủ khác chưa được phân vào đâu',	'phuongchau',	't'),
('314',	'Nhân viên về luật pháp',	'phuongchau',	't'),
('315',	'Nhân viên về công tác xã hội',	'phuongchau',	't'),
('316',	'Nhân viên về tôn giáo',	'phuongchau',	't'),
('317',	'Vận động viên và người chơi thể thao',	'phuongchau',	't'),
('318',	'Huấn luyện viên thể thao',	'phuongchau',	't'),
('319',	'Nhân viên hướng dẫn thể dục thẩm mỹ',	'phuongchau',	't'),
('320',	'Nhân viên hướng dẫn tập thể hình',	'phuongchau',	't'),
('321',	'Nhân viên làm việc trong lĩnh vực thể thao',	'phuongchau',	't'),
('322',	'Huấn luyện viên, nhân viên hướng dẫn thể thao và làm việc trong lĩnh vực thể thao khác',	'phuongchau',	't'),
('323',	'Người hướng dẫn tập luyện và giải trí, người chỉ đạo chương trình',	'phuongchau',	't'),
('324',	'Nhiếp ảnh gia',	'phuongchau',	't'),
('325',	'Nhà thiết kế và trang trí nội thất',	'phuongchau',	't'),
('326',	'Kỹ thuật viên thư viện, viện bảo tàng và triển lãm',	'phuongchau',	't'),
('327',	'Đầu bếp trưởng',	'phuongchau',	't'),
('328',	'Nhân viên về nghệ thuật và văn hóa khác',	'phuongchau',	't'),
('329',	'Kỹ thuật viên vận hành công nghệ thông tin và truyền thông',	'phuongchau',	't'),
('330',	'Kỹ thuật viên hỗ trợ người sử dụng công nghệ thông tin và truyền thông',	'phuongchau',	't'),
('331',	'Kỹ thuật viên hệ thống và mạng máy tính',	'phuongchau',	't'),
('332',	'Kỹ thuật viên web',	'phuongchau',	't'),
('333',	'Kỹ thuật viên điều hành chương trình',	'phuongchau',	't'),
('334',	'Nhân viên điều khiển máy quay phim',	'phuongchau',	't'),
('335',	'Nhân viên điều khiển máy quay hình động/tivi',	'phuongchau',	't'),
('336',	'Nhân viên điều khiển thiết bị phòng thu phát thanh truyền hình',	'phuongchau',	't'),
('337',	'Nhân viên điều khiển thiết bị ghi âm',	'phuongchau',	't'),
('338',	'Nhân viên dựng phim',	'phuongchau',	't'),
('339',	'Các kỹ thuật viên phát thanh và nghe nhìn khác',	'phuongchau',	't'),
('340',	'Kỹ thuật viên kỹ thuật viễn thông',	'phuongchau',	't'),
('341',	'Giáo viên tiểu học',	'phuongchau',	't'),
('342',	'Giáo viên mầm non',	'phuongchau',	't'),
('343',	'Giáo viên dạy các đối tượng bị khuyết tật',	'phuongchau',	't'),
('344',	'Giáo viên sơ cấp',	'phuongchau',	't'),
('345',	'Giáo viên đào tạo khác',	'phuongchau',	't'),
('346',	'Nhân viên văn phòng (gồm cả sắp xếp tài liệu và sao chụp)',	'phuongchau',	't'),
('347',	'Nhân viên nguồn nhân lực/tổ chức',	'phuongchau',	't'),
('348',	'Nhân viên hành chính khác',	'phuongchau',	't'),
('349',	'Thư ký (tổng hợp)',	'phuongchau',	't'),
('350',	'Nhân viên đánh máy',	'phuongchau',	't'),
('351',	'Nhân viên nhập dữ liệu',	'phuongchau',	't'),
('352',	'Nhân viên giao dịch ngân hàng',	'phuongchau',	't'),
('353',	'Nhân viên thu ngân dịch vụ bưu điện',	'phuongchau',	't'),
('354',	'Nhân viên đổi tiền',	'phuongchau',	't'),
('355',	'Nhân viên giao dịch và thu ngân khác',	'phuongchau',	't'),
('356',	'Nhân viên chia bài trong sòng bạc và các nghề liên quan đến cờ bạc khác',	'phuongchau',	't'),
('357',	'Chủ hiệu cầm đồ',	'phuongchau',	't'),
('358',	'Người cho vay tiền',	'phuongchau',	't'),
('359',	'Người thu nợ',	'phuongchau',	't'),
('360',	'Người thu nợ khác và làm công việc có liên quan',	'phuongchau',	't'),
('361',	'Nhân viên và tư vấn viên du lịch',	'phuongchau',	't'),
('362',	'Nhân viên trung tâm thông tin liên lạc',	'phuongchau',	't'),
('363',	'Nhân viên vận hành tổng đài điện thoại',	'phuongchau',	't'),
('364',	'Nhân viên lễ tân khách sạn',	'phuongchau',	't'),
('365',	'Nhân viên hướng dẫn',	'phuongchau',	't'),
('366',	'Lễ tân (tổng hợp)',	'phuongchau',	't'),
('367',	'Phỏng vấn viên điều tra và nghiên cứu thị trường',	'phuongchau',	't'),
('368',	'Nhân viên thông tin khách hàng chưa được phân vào đâu',	'phuongchau',	't'),
('369',	'Nhân viên kế toán',	'phuongchau',	't'),
('370',	'Nhân viên thống kê, tài chính và bảo hiểm',	'phuongchau',	't'),
('371',	'Nhân viên kế toán tiền lương',	'phuongchau',	't'),
('372',	'Nhân viên ghi chép tồn kho',	'phuongchau',	't'),
('373',	'Nhân viên sản xuất',	'phuongchau',	't'),
('374',	'Nhân viên vận chuyển',	'phuongchau',	't'),
('375',	'Nhân viên thư viện',	'phuongchau',	't'),
('376',	'Nhân viên phân loại và vận chuyển thư',	'phuongchau',	't'),
('377',	'Nhân viên đánh mã, đọc và sửa bản in thử',	'phuongchau',	't'),
('378',	'Người ghi chép thuê và người làm các công việc có liên quan',	'phuongchau',	't'),
('379',	'Nhân viên văn thư và phô tô',	'phuongchau',	't'),
('380',	'Nhân viên tổ chức nhân sự',	'phuongchau',	't'),
('381',	'Nhân viên hỗ trợ văn phòng khác chưa được phân vào đâu',	'phuongchau',	't'),
('382',	'Tiếp viên trên tàu hoặc máy bay',	'phuongchau',	't'),
('383',	'Nhân viên phụ tàu xe',	'phuongchau',	't'),
('384',	'Nhân viên hướng dẫn khu thiên nhiên',	'phuongchau',	't'),
('385',	'Nhân viên hướng dẫn công viên chủ đề',	'phuongchau',	't'),
('386',	'Nhân viên hướng dẫn du lịch khác (như di tích lịch sử, bảo tàng)',	'phuongchau',	't'),
('387',	'Tổ trưởng/Giám sát bồi bàn',	'phuongchau',	't'),
('388',	'Bồi bàn (trừ bồi bàn rượu)',	'phuongchau',	't'),
('389',	'Bồi bàn rượu',	'phuongchau',	't'),
('390',	'Nhân viên pha chế',	'phuongchau',	't'),
('391',	'Thợ làm đầu',	'phuongchau',	't'),
('392',	'Nhân viên làm đẹp và nhân viên có liên quan',	'phuongchau',	't'),
('393',	'Người giám sát việc dọn dẹp và vệ sinh trong văn phòng, khách sạn và các cơ quan khác',	'phuongchau',	't'),
('394',	'Người quản lý công việc gia đình',	'phuongchau',	't'),
('395',	'Người chăm sóc, bảo vệ tòa nhà',	'phuongchau',	't'),
('396',	'Nhà chiêm tinh, nhà tướng số và những người có liên quan đến tâm linh khác',	'phuongchau',	't'),
('397',	'Người bồi phòng và những người được thuê để làm bầu bạn',	'phuongchau',	't'),
('398',	'Người làm nghề phục vụ tang lễ và ướp xác',	'phuongchau',	't'),
('399',	'Nhân viên chăm sóc và làm đẹp động vật',	'phuongchau',	't'),
('400',	'Giáo viên hướng dẫn lái xe',	'phuongchau',	't'),
('401',	'Nhân viên dịch vụ cá nhân khác chưa được phân vào đâu',	'phuongchau',	't'),
('402',	'Người bán hàng trong quầy hàng và tại chợ',	'phuongchau',	't'),
('403',	'Người bán đồ ăn trên đường phố',	'phuongchau',	't'),
('404',	'Chủ cửa hiệu',	'phuongchau',	't'),
('405',	'Nhân viên giám sát cửa hàng',	'phuongchau',	't'),
('406',	'Nhân viên trợ giúp bán hàng',	'phuongchau',	't'),
('407',	'Nhân viên thu ngân và bán vé',	'phuongchau',	't'),
('408',	'Nhân viên thu ngân',	'phuongchau',	't'),
('409',	'Nhân viên thu ngân và bán vé có liên quan khác',	'phuongchau',	't'),
('410',	'Nhân viên làm mẫu',	'phuongchau',	't'),
('411',	'Nhân viên thuyết minh giới thiệu hàng hóa',	'phuongchau',	't'),
('412',	'Nhân viên bán hàng tận nhà',	'phuongchau',	't'),
('413',	'Nhân viên bán hàng qua trung tâm liên lạc',	'phuongchau',	't'),
('414',	'Nhân viên phục vụ ở các trạm dịch vụ',	'phuongchau',	't'),
('415',	'Nhân viên phục vụ đồ ăn uống',	'phuongchau',	't'),
('416',	'Nhân viên bán hàng khác chưa được phân vào đâu',	'phuongchau',	't'),
('418',	'Người phụ tá cho giáo viên',	'phuongchau',	't'),
('419',	'Nhân viên hỗ trợ về chăm sóc sức khỏe',	'phuongchau',	't'),
('420',	'Nhân viên chăm sóc cá nhân (như vật lý trị liệu)',	'phuongchau',	't'),
('421',	'Điều dưỡng tại nhà',	'phuongchau',	't'),
('422',	'Nhân viên chăm sóc cá nhân trong các dịch vụ y tế chưa được phân vào đâu',	'phuongchau',	't'),
('423',	'Nhân viên an ninh (trừ công an)',	'phuongchau',	't'),
('424',	'Thám tử tư',	'phuongchau',	't'),
('425',	'Nhân viên bảo vệ rùng',	'phuongchau',	't'),
('426',	'Nhân viên dịch vụ bảo vệ khác còn lại chưa được phân vào đâu',	'phuongchau',	't'),
('427',	'Lao động trồng, thu hoạch lúa',	'phuongchau',	't'),
('428',	'Lao động trồng, thu hoạch rau các loại',	'phuongchau',	't'),
('429',	'Lao động trồng, thu hoạch cây mùa vụ khác',	'phuongchau',	't'),
('430',	'Lao động trồng, thu hoạch sản phẩm cây cà phê',	'phuongchau',	't'),
('431',	'Lao động trồng, thu hoạch sản phẩm cây chè',	'phuongchau',	't'),
('432',	'Lao động trồng, thu hoạch sản phẩm cây tiêu',	'phuongchau',	't'),
('433',	'Lao động trồng, thu hoạch sản phẩm cây điều',	'phuongchau',	't'),
('434',	'Lao động trồng, thu hoạch sản phẩm cây cao su',	'phuongchau',	't'),
('435',	'Lao động trồng, thu hoạch sản phẩm cây bụi và cây thân gỗ khác',	'phuongchau',	't'),
('436',	'Lao động trồng, thu hoạch hoa, cây cảnh',	'phuongchau',	't'),
('437',	'Lao động làm vườn, trồng vườn và vườn ươm khác',	'phuongchau',	't'),
('438',	'Lao động trồng trọt hỗn hợp',	'phuongchau',	't'),
('439',	'Lao động chăn nuôi trâu bò',	'phuongchau',	't'),
('440',	'Lạo động chăn nuôi dê, cừu, hươu',	'phuongchau',	't'),
('441',	'Lao động chăn nuôi lợn',	'phuongchau',	't'),
('442',	'Lao động chăn nuôi gia súc khác',	'phuongchau',	't'),
('443',	'Lao động chăn nuôi gà',	'phuongchau',	't'),
('444',	'Lao động chăn nuôi vịt, ngan, ngỗng',	'phuongchau',	't'),
('445',	'Lao động chăn nuôi gia cầm khác',	'phuongchau',	't'),
('446',	'Lao động nuôi ong',	'phuongchau',	't'),
('447',	'Lao động nuôi tằm',	'phuongchau',	't'),
('448',	'Lao động chăn nuôi chưa được phân vào đâu',	'phuongchau',	't'),
('449',	'Lao động trồng trọt và chăn nuôi hỗn hợp',	'phuongchau',	't'),
('450',	'Lao động ươm giống cây lâm nghiệp',	'phuongchau',	't'),
('451',	'Lao động trồng rừng và chăm sóc rừng lấy gỗ',	'phuongchau',	't'),
('452',	'Lao động trồng rừng và chăm sóc rừng tre, nứa',	'phuongchau',	't'),
('453',	'Lao động trong lâm nghiệp và lĩnh vực có liên quan khác',	'phuongchau',	't'),
('454',	'Lao động nuôi cá',	'phuongchau',	't'),
('455',	'Lao động nuôi tôm',	'phuongchau',	't'),
('456',	'Lao động nuôi trồng thủy sản khác',	'phuongchau',	't'),
('457',	'Lao động khai thác cá trong nội địa',	'phuongchau',	't'),
('458',	'Lao động khai thác thủy sản khác trong nội địa',	'phuongchau',	't'),
('459',	'Lao động khai thác cá trong vùng biển Việt Nam',	'phuongchau',	't'),
('460',	'Lao động khai thác thủy sản khác trong vùng biển Việt Nam',	'phuongchau',	't'),
('461',	'Lao động săn bắn, đánh bẫy',	'phuongchau',	't'),
('462',	'Lao động trồng trọt tự cung tự cấp',	'phuongchau',	't'),
('463',	'Lao động chăn nuôi gia súc tự cung tự cấp',	'phuongchau',	't'),
('464',	'Lao động trồng trọt và chăn nuôi hỗn hợp tự cung tự cấp',	'phuongchau',	't'),
('465',	'Lao động đánh cá, săn bắn, đánh bẫy và thu hái tự cung tự cấp',	'phuongchau',	't'),
('466',	'Thợ xây nhà',	'phuongchau',	't'),
('467',	'Thợ nề và các thợ có liên quan',	'phuongchau',	't'),
('468',	'Thợ đẽo đá/thợ khắc đá',	'phuongchau',	't'),
('469',	'Thợ xây nhà bằng đá',	'phuongchau',	't'),
('470',	'Thợ đổ bê tông cốt thép (chung)',	'phuongchau',	't'),
('471',	'Thợ bê tông',	'phuongchau',	't'),
('472',	'Thợ bê tông khác, thợ hoàn thiện bê tông và thợ liên quan khác',	'phuongchau',	't'),
('473',	'Thợ mộc và thợ làm đồ gỗ',	'phuongchau',	't'),
('474',	'Thợ giàn giáo',	'phuongchau',	't'),
('475',	'Thợ phá dỡ',	'phuongchau',	't'),
('476',	'Thợ ốp tường',	'phuongchau',	't'),
('477',	'Thợ xây khác và thợ có liên quan chưa được phân vào đâu',	'phuongchau',	't'),
('478',	'Thợ lợp mái',	'phuongchau',	't'),
('479',	'Thợ lát sàn và thợ lát đá',	'phuongchau',	't'),
('480',	'Thợ thạch cao',	'phuongchau',	't'),
('481',	'Thợ lắp đặt cách điện xây dựng',	'phuongchau',	't'),
('482',	'Thợ nồi hơi/thợ ống cách điện',	'phuongchau',	't'),
('483',	'Thợ lắp đặt cách điện thiết bị điều hòa không khí',	'phuongchau',	't'),
('484',	'Thợ lắp đặt vật liệu chịu lửa',	'phuongchau',	't'),
('485',	'Thợ lắp đặt vật liệu cách âm, cách nhiệt khác',	'phuongchau',	't'),
('486',	'Thợ lắp kính',	'phuongchau',	't'),
('487',	'Thợ ống nước',	'phuongchau',	't'),
('488',	'Thợ cơ khí thiết bị điều hòa không khí và làm lạnh',	'phuongchau',	't'),
('489',	'Thợ sơn',	'phuongchau',	't'),
('490',	'Thợ dán giấy dán tường/trần',	'phuongchau',	't'),
('491',	'Thợ sơn kết cấu thép/sơn tàu',	'phuongchau',	't'),
('492',	'Thợ phun sơn xe cơ giới',	'phuongchau',	't'),
('493',	'Thợ vẽ bảng hiệu',	'phuongchau',	't'),
('494',	'Thợ phun sơn (trừ tàu, xe cơ giới và biển báo)',	'phuongchau',	't'),
('495',	'Thợ sơn khác và thợ có liên quan',	'phuongchau',	't'),
('496',	'Người lau dọn tòa nhà',	'phuongchau',	't'),
('497',	'Thợ tạo khuôn và lõi kim loại',	'phuongchau',	't'),
('498',	'Thợ hàn',	'phuongchau',	't'),
('499',	'Thợ cắt kim loại bằng nhiệt',	'phuongchau',	't'),
('500',	'Thợ luyện kim loại',	'phuongchau',	't'),
('501',	'Thợ chuẩn bị và lắp ráp các cấu kiện kim loại',	'phuongchau',	't'),
('502',	'Thợ lắp ráp và thợ nối cáp',	'phuongchau',	't'),
('503',	'Thợ rèn, thợ quai búa và thợ rèn ép nén kim loại',	'phuongchau',	't'),
('504',	'Thợ chế tạo dụng cụ và thợ có liên quan',	'phuongchau',	't'),
('505',	'Thợ lắp ráp và vận hành máy công cụ kim loại',	'phuongchau',	't'),
('506',	'Thợ đánh bóng, thợ mài kim loại và dụng cụ kim loại',	'phuongchau',	't'),
('507',	'Thợ cơ khí xe có động cơ',	'phuongchau',	't'),
('508',	'Thợ sửa chữa xe có động cơ',	'phuongchau',	't'),
('509',	'Thợ cơ khí máy bay',	'phuongchau',	't'),
('510',	'Thợ sửa chữa động cơ máy bay',	'phuongchau',	't'),
('511',	'Thợ cơ khí máy móc (chung)',	'phuongchau',	't'),
('512',	'Thợ sửa chữa máy móc (chung)',	'phuongchau',	't'),
('513',	'Thợ cơ khí máy móc công nghiệp/máy văn phòng',	'phuongchau',	't'),
('514',	'Thợ sửa chữa động cơ biển',	'phuongchau',	't'),
('515',	'Thợ lắp đặt máy móc, thiết bị',	'phuongchau',	't'),
('516',	'Thợ cơ khí và sửa chữa máy móc khác (như thợ cơ khí máy móc nông nghiệp)',	'phuongchau',	't'),
('517',	'Thợ sửa chữa xe đạp và thợ có liên quan',	'phuongchau',	't'),
('518',	'Thợ sản xuất và sửa chữa dụng cụ chính xác',	'phuongchau',	't'),
('519',	'Thợ sản xuất và điều chỉnh nhạc cụ',	'phuongchau',	't'),
('520',	'Thợ kim hoàn (nói chung)',	'phuongchau',	't'),
('521',	'Thợ cắt và đánh bóng đá quý',	'phuongchau',	't'),
('522',	'Thợ vàng/thợ bạc',	'phuongchau',	't'),
('523',	'Thợ khắc kim hoàn',	'phuongchau',	't'),
('524',	'Thợ kim hoàn khác',	'phuongchau',	't'),
('525',	'Thợ gốm',	'phuongchau',	't'),
('526',	'Thợ gạch ngói',	'phuongchau',	't'),
('527',	'Thợ gốm và thợ có liên quan khác',	'phuongchau',	't'),
('528',	'Thợ sản xuất, thợ cắt, thợ mài và thợ hoàn thiện đồ thủy tinh',	'phuongchau',	't'),
('529',	'Thợ khắc thủy tinh/thợ khắc axit',	'phuongchau',	't'),
('530',	'Thợ vẽ/thợ trang trí thủy tinh và gốm',	'phuongchau',	't'),
('531',	'Thợ vẽ biển quảng cáo, thợ trang trí, thợ khắc và thợ khắc axit khác',	'phuongchau',	't'),
('532',	'Thợ thủ công sản xuất đồ gỗ, rổ rá và các nguyên liệu có liên quan',	'phuongchau',	't'),
('533',	'Thợ thủ công dệt vải, da và các nguyên liệu có liên quan',	'phuongchau',	't'),
('534',	'Thợ thủ công khác chưa được phân vào đâu',	'phuongchau',	't'),
('535',	'Thợ thực hiện công đoạn trước in',	'phuongchau',	't'),
('536',	'Thợ in offset, in lõm, in cao, in lưới và in kỹ thuật số',	'phuongchau',	't'),
('537',	'Thợ in khác',	'phuongchau',	't'),
('538',	'Thợ hoàn thiện sản phẩm in',	'phuongchau',	't'),
('539',	'Thợ lắp điện cho tòa nhà và thợ điện có liên quan',	'phuongchau',	't'),
('540',	'Thợ lắp ráp điện (chung)',	'phuongchau',	't'),
('541',	'Thợ lắp ráp điện thang máy, thang cuốn và các thiết bị liên quan',	'phuongchau',	't'),
('542',	'Thợ sửa chữa điện gia dụng',	'phuongchau',	't'),
('543',	'Thơ lắp ráp và thợ cơ khí điện khác',	'phuongchau',	't'),
('544',	'Thợ lắp đặt đường dây điện',	'phuongchau',	't'),
('545',	'Thợ ghép cáp điện',	'phuongchau',	't'),
('546',	'Thợ lắp đặt và sửa chữa đường dây điện khác',	'phuongchau',	't'),
('547',	'Thợ lắp đặt thiết bị điện tử (chung)',	'phuongchau',	't'),
('548',	'Thợ cơ khí thiết bị video và âm thanh',	'phuongchau',	't'),
('549',	'Thợ lắp đặt thiết bị điện tử khác',	'phuongchau',	't'),
('550',	'Thợ lắp đặt phát sóng rada, phát thanh truyền hình/thiết bị truyền dẫn',	'phuongchau',	't'),
('551',	'Thợ lắp đặt và sửa chữa máy tính và thiết bị điện tử liên quan',	'phuongchau',	't'),
('552',	'Thợ kéo dây cáp viễn thông',	'phuongchau',	't'),
('553',	'Thợ cài đặt viễn thông/dịch vụ viễn thông',	'phuongchau',	't'),
('554',	'Thợ giết mổ',	'phuongchau',	't'),
('555',	'Thợ giết mổ, chuẩn bị thịt, cá và thực phẩm khác có liên quan',	'phuongchau',	't'),
('556',	'Thợ làm bánh (chung)',	'phuongchau',	't'),
('557',	'Thợ làm bánh mỳ',	'phuongchau',	't'),
('558',	'Thợ làm bánh ngọt và bánh kẹo',	'phuongchau',	't'),
('559',	'Thợ làm sản phẩm từ sữa',	'phuongchau',	't'),
('560',	'Thợ bảo quản rau, hoa quả tươi và các thứ có liên quan',	'phuongchau',	't'),
('561',	'Thợ nếm cà phê và trà',	'phuongchau',	't'),
('562',	'Thợ nếm và phân loại đồ uống, thực phẩm khác',	'phuongchau',	't'),
('563',	'Thợ sản xuất và chuẩn bị thuốc lá',	'phuongchau',	't'),
('564',	'Thợ lò sấy',	'phuongchau',	't'),
('565',	'Thợ xử lý gỗ',	'phuongchau',	't'),
('566',	'Thợ xử lý gỗ khác',	'phuongchau',	't'),
('567',	'Thợ sản xuất đồ nội thất',	'phuongchau',	't'),
('568',	'Thợ hoàn thiện đồ gỗ',	'phuongchau',	't'),
('569',	'Thợ sản xuất khung hình',	'phuongchau',	't'),
('570',	'Thợ sản xuất đồ gỗ và các thợ có liên quan khác',	'phuongchau',	't'),
('571',	'Thợ lắp đặt và vận hành máy công cụ chế biến gỗ',	'phuongchau',	't'),
('572',	'Thợ may, thợ làm da thủ và thợ làm mũ',	'phuongchau',	't'),
('573',	'Thợ tạo mẫu',	'phuongchau',	't'),
('574',	'Thợ cắt',	'phuongchau',	't'),
('575',	'Thợ tạo và cắt mẫu áo quần và các mẫu có liên quan khác',	'phuongchau',	't'),
('576',	'Thợ khâu vá, thợ thêu và các thợ có liên quan',	'phuongchau',	't'),
('577',	'Thợ làm nghề bọc đồ đạc và các thợ có liên quan',	'phuongchau',	't'),
('578',	'Thợ thuộc da sống, thợ nhuộm và thợ chuyên lột da, lông thú',	'phuongchau',	't'),
('579',	'Thợ đóng giày',	'phuongchau',	't'),
('580',	'Thợ sản xuất giày chỉnh hình',	'phuongchau',	't'),
('581',	'Thợ vá giày',	'phuongchau',	't'),
('582',	'Thợ sản xuất/lắp ráp hàng da',	'phuongchau',	't'),
('583',	'Thợ đóng giày và các thợ có liên quan khác',	'phuongchau',	't'),
('584',	'Thợ lặn',	'phuongchau',	't'),
('585',	'Thợ giật mìn phá đá',	'phuongchau',	't'),
('586',	'Thợ phân loại và kiểm tra sản phẩm (trừ thực phẩm và đồ uống)',	'phuongchau',	't'),
('587',	'Thợ hun khói và thợ kiểm soát thực vật, động vật có hại khác',	'phuongchau',	't'),
('588',	'Thợ thủ công và các thợ khác chưa được phân vào đâu',	'phuongchau',	't'),
('589',	'Thợ khai thác mỏ và đá',	'phuongchau',	't'),
('590',	'Thợ vận hành thiết bị chế biến khoáng sản và đá',	'phuongchau',	't'),
('591',	'Thợ khoan giếng (giếng dầu khí)',	'phuongchau',	't'),
('592',	'Thợ khoan giếng (trừ giếng dầu khí)',	'phuongchau',	't'),
('593',	'Thợ vận hành máy khoan sâu',	'phuongchau',	't'),
('594',	'Thợ khoan, đào giếng và các thợ có liên quan khác',	'phuongchau',	't'),
('595',	'Thợ vận hành máy sản xuất sản phẩm bê tông đúc sẵn',	'phuongchau',	't'),
('596',	'Thợ vận hành máy sản xuất xi măng amiăng',	'phuongchau',	't'),
('597',	'Thợ vận hành máy làm gạch đất nung, ngói',	'phuongchau',	't'),
('598',	'Thợ vận hành máy trộn bê tông',	'phuongchau',	't'),
('599',	'Thợ vận hành bơm bê tông',	'phuongchau',	't'),
('600',	'Thợ vận hành máy chế biến và các sản phẩm khoáng sản khác',	'phuongchau',	't'),
('601',	'Thợ vận hành thiết bị xử lý kim loại',	'phuongchau',	't'),
('602',	'Thợ vận hành máy hoàn thiện, tráng, mạ kim loại',	'phuongchau',	't'),
('603',	'Thợ vận hành thiết bị nghiền/trộn hóa chất',	'phuongchau',	't'),
('604',	'Thợ vận hành máy xử lý nhiệt hóa học',	'phuongchau',	't'),
('605',	'Thợ vận hành máy lọc và tách hóa chất',	'phuongchau',	't'),
('606',	'Thợ vận hành hóa chất tĩnh/lò phản ứng',	'phuongchau',	't'),
('607',	'Thợ vận hành máy sợi tổng hợp',	'phuongchau',	't'),
('608',	'Thợ vận hành máy và thiết bị sản xuất hóa học khác',	'phuongchau',	't'),
('609',	'Thợ vận hành máy sản xuất sản phẩm phim ảnh',	'phuongchau',	't'),
('610',	'Thợ vận hành máy phay cao su',	'phuongchau',	't'),
('611',	'Thợ vận hành máy cán cao su',	'phuongchau',	't'),
('612',	'Thợ vận hành máy sản xuất sản phẩm cao su khác',	'phuongchau',	't'),
('613',	'Thợ vận hành máy sản xuất sản phẩm nhựa',	'phuongchau',	't'),
('614',	'Thợ vận hành máy làm thùng catong/hộp giấy',	'phuongchau',	't'),
('615',	'Thợ vận hành máy sản xuất sản phẩm giấy',	'phuongchau',	't'),
('616',	'Thợ vận hành máy sản xuất sản phẩm giấy và thùng catong khác',	'phuongchau',	't'),
('617',	'Thợ vận hành máy xe chỉ (chỉ và sợi)',	'phuongchau',	't'),
('618',	'Thợ vận hành máy cuộn chỉ (chỉ và sợi)',	'phuongchau',	't'),
('619',	'Thợ vận hành máy dệt',	'phuongchau',	't'),
('620',	'Thợ vận hành máy đan',	'phuongchau',	't'),
('621',	'Thợ vận hành máy may',	'phuongchau',	't'),
('622',	'Thợ vận hành máy thêu',	'phuongchau',	't'),
('623',	'Thợ vận hành máy tẩy trắng',	'phuongchau',	't'),
('624',	'Thợ vận hành máy nhuộm',	'phuongchau',	't'),
('625',	'Thợ vận hành máy làm sạch sợi',	'phuongchau',	't'),
('626',	'Thợ vận hành máy tẩy trắng, máy nhuộm và làm sạch sợi khác',	'phuongchau',	't'),
('627',	'Thợ vận hành máy chuẩn bị da, lông thú',	'phuongchau',	't'),
('628',	'Thợ vận hành máy đóng giầy, dép và các thợ có liên quan',	'phuongchau',	't'),
('629',	'Thợ vận hành máy giặt là',	'phuongchau',	't'),
('630',	'Thợ vận hành máy sản xuất nguyên liệu dệt, da lông thú và da thuộc chưa được phân vào đâu',	'phuongchau',	't'),
('631',	'Thợ vận hành máy sản xuất các sản phẩm từ thịt và cá',	'phuongchau',	't'),
('632',	'Thợ vận hành máy sản xuất sữa và bánh kẹo',	'phuongchau',	't'),
('633',	'Thợ vận hành máy xay ngũ cốc và gia vị',	'phuongchau',	't'),
('634',	'Thợ vận hành máy nướng và các sản phẩm từ ngũ cốc',	'phuongchau',	't'),
('635',	'Thợ vận hành máy sản xuất các sản phẩm từ trái cây, rau quả',	'phuongchau',	't'),
('636',	'Thợ vận hành máy chế biến và tinh chế đường',	'phuongchau',	't'),
('637',	'Thợ vận hành máy sản xuất bia, rượu và nước giải khát khác',	'phuongchau',	't'),
('638',	'Thợ vận hành máy sản xuất thuốc lá',	'phuongchau',	't'),
('639',	'Thợ vận hành máy sản xuất thực phẩm và các thợ có liên quan chưa được phân vào đâu',	'phuongchau',	't'),
('640',	'Thợ vận hành thiết bị chế tạo bột giấy',	'phuongchau',	't'),
('641',	'Thợ vận hành thiết bị chế tạo giấy',	'phuongchau',	't'),
('642',	'Thợ vận hành thiết bị chế tạo bột giấy và giấy',	'phuongchau',	't'),
('643',	'Thợ cưa',	'phuongchau',	't'),
('644',	'Thợ vận hành máy cắt',	'phuongchau',	't'),
('645',	'Thợ sơn lõi ván ép',	'phuongchau',	't'),
('646',	'Thợ vận hành máy ép ván ép',	'phuongchau',	't'),
('647',	'Thợ phân loại gỗ',	'phuongchau',	't'),
('648',	'Thợ vận hành máy chế biến gỗ',	'phuongchau',	't'),
('649',	'Thợ vận hành máy cưa gỗ chính xác',	'phuongchau',	't'),
('650',	'Thợ vận hành thiết bị chế biến gỗ khác',	'phuongchau',	't'),
('651',	'Thợ vận hành lò nung thủy tinh/gốm',	'phuongchau',	't'),
('652',	'Thợ sản xuất sợi thủy tinh',	'phuongchau',	't'),
('653',	'Thợ vận hành thiết bị sản xuất thủy tinh và gốm',	'phuongchau',	't'),
('654',	'Thợ vận hành động cơ hơi nước',	'phuongchau',	't'),
('655',	'Thợ đốt lò',	'phuongchau',	't'),
('656',	'Thợ vận hành động cơ hơi nước và nồi hơi khác',	'phuongchau',	't'),
('657',	'Thợ vận hành thiết bị đóng gói, đóng chai và dán nhãn',	'phuongchau',	't'),
('658',	'Thợ vận hành máy in, máy đóng sách và máy có liên quan',	'phuongchau',	't'),
('659',	'Thợ vận hành máy cắt dây cáp và dây tải điện',	'phuongchau',	't'),
('660',	'Thợ vận hành máy sản xuất con chip silicon',	'phuongchau',	't'),
('661',	'Thợ vận hành dây chuyền lắp ráp tự động và vận hành rô bốt công nghiệp',	'phuongchau',	't'),
('662',	'Thợ vận hành thiết bị khác chưa được phân vào đâu',	'phuongchau',	't'),
('663',	'Thợ lắp ráp máy cơ khí',	'phuongchau',	't'),
('664',	'Thợ lắp ráp thiết bị điện/linh kiện điện',	'phuongchau',	't'),
('665',	'Thợ lắp ráp thiết bị điện tử/linh kiện điện tử',	'phuongchau',	't'),
('666',	'Thợ lắp ráp pin',	'phuongchau',	't'),
('667',	'Thợ lắp ráp đồ chơi',	'phuongchau',	't'),
('668',	'Thợ lắp ráp khác chưa được phân vào đâu (lắp ráp sản phẩm nhựa, lắp ráp sản phẩm cao su)',	'phuongchau',	't'),
('669',	'Lái các phương tiện vận chuyển trên đường ray',	'phuongchau',	't'),
('670',	'Nhân viên điều khiển tín hiệu, bẻ ghi và chuyển hướng tàu hỏa',	'phuongchau',	't'),
('671',	'Nhân viên điều khiển tín hiệu, bẻ ghi và chuyển hướng tàu hỏa',	'phuongchau',	't'),
('672',	'Nhân viên đường sắt khác và nhân viên có liên quan',	'phuongchau',	't'),
('673',	'Người chở người, chở hàng bằng xe máy (không phải là thư)',	'phuongchau',	't'),
('674',	'Người chở người, chở hàng bằng xe máy sử dụng các thiết bị di động cá nhân (lái xe máy công nghệ)',	'phuongchau',	't'),
('675',	'Lái xe taxi',	'phuongchau',	't'),
('676',	'Lái xe con',	'phuongchau',	't'),
('677',	'Lái xe tải hạng nhẹ',	'phuongchau',	't'),
('678',	'Lái xe cứu thương',	'phuongchau',	't'),
('679',	'Người trông bãi đỗ xe',	'phuongchau',	't'),
('680',	'Lái xe con và xe hạng nhẹ khác',	'phuongchau',	't'),
('681',	'Lái xe buýt',	'phuongchau',	't'),
('682',	'Lái xe điện',	'phuongchau',	't'),
('683',	'Lái xe tải hạng nặng',	'phuongchau',	't'),
('684',	'Lái xe tải rơ móoc (bao gồm cả lái xe chính)',	'phuongchau',	't'),
('685',	'Lái xe cứu hỏa',	'phuongchau',	't'),
('686',	'Lái thiết bị di động sân bay',	'phuongchau',	't'),
('687',	'Lái xe tải trộn bê tông',	'phuongchau',	't'),
('688',	'Lái xe tải chở chất thải (bao gồm cả xe tải móc với thùng chứa cuộn)',	'phuongchau',	't'),
('689',	'Lái xe tải hạng vừa và xe tải hạng nặng khác',	'phuongchau',	't'),
('690',	'Thợ vận hành thiết bị nông nghiệp và lâm nghiệp',	'phuongchau',	't'),
('691',	'Thợ vận hành máy đào',	'phuongchau',	't'),
('692',	'Thợ vận hành máy ủi',	'phuongchau',	't'),
('693',	'Thợ vận hành máy nạo vét',	'phuongchau',	't'),
('694',	'Thợ vận hành máy đóng cọc/máy khoan',	'phuongchau',	't'),
('695',	'Thợ vận hành máy làm đường',	'phuongchau',	't'),
('696',	'Thợ vận hành máy đào hầm (kể cả thợ vận hành máy kích ống)',	'phuongchau',	't'),
('697',	'Thợ vận hành máy đào đất và thợ vận hành thiết bị có liên quan khác',	'phuongchau',	't'),
('698',	'Thợ vận hành cần trục (chung)',	'phuongchau',	't'),
('699',	'Thợ vận hành cần trục (hải cảng)',	'phuongchau',	't'),
('700',	'Thợ vận hành cần trục và thợ vận hành các thiết bị có liên quan khác',	'phuongchau',	't'),
('701',	'Thợ vận hành xe bốc dỡ',	'phuongchau',	't'),
('702',	'Người lái tàu',	'phuongchau',	't'),
('703',	'Thủy thủ (bao gồm cả người chủ tàu)',	'phuongchau',	't'),
('704',	'Thủy thủ trên tàu và những thợ có liên quan khác',	'phuongchau',	't'),
('705',	'Người giúp việc gia đình (chung)',	'phuongchau',	't'),
('706',	'Người quét dọn và giúp việc gia đình khác',	'phuongchau',	't'),
('707',	'Người dọn dẹp văn phòng',	'phuongchau',	't'),
('708',	'Người dọn dẹp khách sạn',	'phuongchau',	't'),
('709',	'Người dọn dẹp cơ sở công nghiệp',	'phuongchau',	't'),
('710',	'Người dọn dẹp cơ sở thực phẩm và đồ uống (như nhà hàng, trung tâm bán hàng rong)',	'phuongchau',	't'),
('711',	'Người dọn dẹp khu dân cư (như chung cư, căn hộ riêng, khu vực chung trong khu dân cư)',	'phuongchau',	't'),
('712',	'Người dọn dẹp khu vực công cộng (như trạm dừng xe buýt, đường sắt, cống rãnh, cầu trên cao, đường giao thông, đường cao tốc, công viên, bãi biển)',	'phuongchau',	't'),
('713',	'Người dọn dẹp các phương tiện (như máy bay, tàu hỏa, tàu điện ngầm)',	'phuongchau',	't'),
('714',	'Người dọn dẹp ở các cơ sở khác (như trung tâm mua sắm, trường học, bệnh viện, những nơi thờ tự)',	'phuongchau',	't'),
('715',	'Thợ giặt là bằng tay',	'phuongchau',	't'),
('716',	'Thợ rửa xe cộ',	'phuongchau',	't'),
('717',	'Thợ làm sạch cửa sổ',	'phuongchau',	't'),
('718',	'Thợ lau dọn khác',	'phuongchau',	't'),
('719',	'Lao động trồng trọt',	'phuongchau',	't'),
('720',	'Lao động chăn nuôi',	'phuongchau',	't'),
('721',	'Lao động trồng trọt và chăn nuôi hỗn hợp',	'phuongchau',	't'),
('722',	'Lao động làm vườn',	'phuongchau',	't'),
('723',	'Lao động lâm nghiệp',	'phuongchau',	't'),
('724',	'Lao động thủy sản',	'phuongchau',	't'),
('725',	'Lao động nuôi trồng thủy sản',	'phuongchau',	't'),
('726',	'Lao động khai thác thủy sản trong nội địa',	'phuongchau',	't'),
('727',	'Lao động khai thác thủy sản trong vùng biển Việt Nam',	'phuongchau',	't'),
('728',	'Lao động trong khai thác mỏ và khai thác đá',	'phuongchau',	't'),
('729',	'Lao động trong xây dựng công trình kỹ thuật (không phải nhà)',	'phuongchau',	't'),
('730',	'Thợ phụ xây dựng',	'phuongchau',	't'),
('731',	'Lao động đóng gói thủ công',	'phuongchau',	't'),
('732',	'Lao động công nghiệp khác chưa được phân vào đâu',	'phuongchau',	't'),
('733',	'Lái xe bằng tay và đạp chân',	'phuongchau',	't'),
('734',	'Người điều khiển máy kéo và phương tiện do gia súc kéo',	'phuongchau',	't'),
('735',	'Người mang vác hàng hóa xuống tàu và lên bờ',	'phuongchau',	't'),
('736',	'Người mang vác đường sắt/đường bộ',	'phuongchau',	't'),
('737',	'Người bốc xếp máy bay (như hành lý sân bay/xử lý hàng hóa)',	'phuongchau',	't'),
('738',	'Người bốc xếp tại kho',	'phuongchau',	't'),
('739',	'Người phục vụ xe vận chuyển hàng hóa',	'phuongchau',	't'),
('740',	'Người đẩy hàng',	'phuongchau',	't'),
('741',	'Người buộc dây hàng hóa',	'phuongchau',	't'),
('742',	'Người mang vác hàng khác',	'phuongchau',	't'),
('743',	'Người bày hàng lên giá',	'phuongchau',	't'),
('744',	'Người chuẩn bị đồ ăn nhanh',	'phuongchau',	't'),
('745',	'Người phụ bếp',	'phuongchau',	't'),
('746',	'Lao động trên đường phố và lao động có liên quan',	'phuongchau',	't'),
('747',	'Người bán hàng rong trên đường phố (trừ đồ ăn)',	'phuongchau',	't'),
('748',	'Người thu gom rác và tái chế',	'phuongchau',	't'),
('749',	'Người thu dọn, sắp xếp, phân loại rác',	'phuongchau',	't'),
('750',	'Người quét dọn và lao động khác có liên quan',	'phuongchau',	't'),
('751',	'Người đưa thư',	'phuongchau',	't'),
('752',	'Người giao hàng',	'phuongchau',	't'),
('753',	'Người khuân vác ở khách sạn',	'phuongchau',	't'),
('754',	'Người khuân vác (trừ khách sạn)',	'phuongchau',	't'),
('755',	'Người làm công việc lặt vặt',	'phuongchau',	't'),
('756',	'Người đọc đồng hồ đo và người thu tiền từ máy bán hàng tự động',	'phuongchau',	't'),
('757',	'Người thu gom nước và củi',	'phuongchau',	't'),
('758',	'Lao động giản đơn khác chưa được phân vào đâu',	'phuongchau',	't'),
('759',	'Lực lượng vũ trang',	'phuongchau',	't'),
('760',	'Sĩ quan',	'phuongchau',	't'),
('761',	'Hạ sĩ quan, binh sĩ',	'phuongchau',	't'),
('762',	'Lực lượng khác trong quân đội',	'phuongchau',	't'),
('763',	'Sĩ quan',	'phuongchau',	't'),
('764',	'Hạ sĩ quan, chiến sĩ',	'phuongchau',	't'),
('765',	'Lực lượng khác trong công an',	'phuongchau',	't'),
('766',	'Cơ yếu',	'phuongchau',	't'),
('767',	'Lực lượng vũ trang khác',	'phuongchau',	't');